In [1]:
import numpy as np

a = np.arange(1, 21)
print(a)
print(a.ndim, a.shape, a.size, a.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1 (20,) 20 int64


In [2]:
import numpy as np

np.random.seed(0)
a = np.random.randint(0, 51, (4, 5))
print(a)
print(a.itemsize, a.nbytes)

[[44 47  0  3  3]
 [39  9 19 21 50]
 [36 23  6 24 24]
 [12  1 38 39 23]]
4 80


In [3]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)

print(a[1, 2])   
print(a[-1])     
print(a[:, -1])  

7
[ 9 10 11 12]
[ 4  8 12]


In [4]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)

print(a[:2, :2])  
print(a[:, ::2])  
print(a[:, ::-1]) 

[[1 2]
 [5 6]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [5]:
import numpy as np

a = np.arange(12).reshape(3,4)

v = a[:2, :2]
v[0,0] = 99
print(a)

c = a[:2, :2].copy()
c[0,0] = 100
print(a)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
import numpy as np

x = np.arange(12)

print(x.reshape(3,4))

a = x.reshape(12,1)
b = x[:, np.newaxis]

print(np.array_equal(a,b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
True


In [7]:
import numpy as np

a = np.random.randint(10, size=(2,3))
b = np.random.randint(10, size=(2,3))

print(np.vstack((a,b)))
print(np.concatenate((a,b), axis=0))

print(np.hstack((a,b)))
print(np.concatenate((a,b), axis=1))

[[8 1 5]
 [9 8 9]
 [4 3 0]
 [3 5 0]]
[[8 1 5]
 [9 8 9]
 [4 3 0]
 [3 5 0]]
[[8 1 5 4 3 0]
 [9 8 9 3 5 0]]
[[8 1 5 4 3 0]
 [9 8 9 3 5 0]]


In [8]:
import numpy as np

a = np.arange(1,16)

x = np.split(a,3)

print(x[0])
print(x[1])
print(x[2])

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
