In [4]:
import numpy as n 
n.array(type([10,20,30,40,50]))


array(<class 'list'>, dtype=object)

In [8]:
import numpy as n 
n.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
import numpy as n 
aee=n.array([7,8,9],dtype=float)
print(type(aee))

<class 'numpy.ndarray'>


In [18]:
import numpy as n 
arr1=n.zeros(6)
arr2=n.zeros((3,2),dtype=int)
print(arr1,arr2)

[0. 0. 0. 0. 0. 0.] [[0 0]
 [0 0]
 [0 0]]


In [19]:
import numpy as np 
np.empty((2,2))  //it gives garbage values and empty allocates free space so prefered over zeros and  the garbage values will be there before in zeros it is replaced so it is faster 

array([[2.12199579e-314, 1.09919382e-311],
       [6.22522714e-321, 1.09919382e-311]])

In [23]:
import numpy as n 
n.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
import numpy as n 
n.linspace(0,1,6)  //in inspace the 1 is inclusive but not in arange it is inclusive 

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
import numpy as n 
n.random.random((3,3))

array([[0.7936571 , 0.90941421, 0.41518147],
       [0.89725201, 0.7680489 , 0.27030422],
       [0.88883154, 0.08941892, 0.12925151]])